export class ConsultaCnpj {
    orderFactory_Id:string;
    order_Id:string;
    invoice:any;
    dt_invoice:any;
    dt_invoice_relat:any;
    brand_name:string;
    total_quantity:string;
    total_price:string;
    packed_quantity:string;
    packed_price:string;
    total_quantity_invoiced:string;
    total_price_invoiced:string;
    percentual_invoiced:string;
    customer_name:string;
    customerFab_Id:string;
    blockedBy:string;
    company_doc:string;
}